#!/usr/bin/env python3
"""Render exp3/features/feature_evidence.json into reports3/feat-univariate.md.

Reads only the JSON kv_ttl_feature_univariate.py already wrote -- never touches the DB, so
this can be re-run (or handed to someone else) without re-measuring anything.

Usage:
    python3 kv_ttl_featureuni_report.py --in-json .../feature_evidence.json \
        --plots-rel plots --out .../feat-univariate.md
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def fmt_usd(v) -> str:
    if v is None:
        return "n/a"
    return f"${v:,.2f}"


def fmt_q(v) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "n/a"
    return f"{v:.3g}"


def feature_row(f: dict) -> str:
    cov = f["coverage"]
    c = f["outcomes"].get("c_dollar_value") or {}
    q_c = (f.get("fdr") or {}).get("c_dollar_value")
    ci = c.get("ci95", [None, None])
    f5 = c.get("vs_fixed_5m", {})
    ci5 = f5.get("ci95", [None, None])
    return (f"| {f['catalogue_name']} | {f['availability']} | "
           f"{cov['n_non_missing']:,} ({cov['pct_missing']:.1f}% missing) | "
           f"{fmt_usd(f5.get('point'))} [{fmt_usd(ci5[0])}, {fmt_usd(ci5[1])}] | "
           f"{fmt_usd(c.get('point'))} [{fmt_usd(ci[0])}, {fmt_usd(ci[1])}] | "
           f"{fmt_q(q_c)} | **{f['verdict']}** |")


def build(ev: dict, plots_rel: str) -> str:
    b = []
    b.append("# Feature univariate evidence\n")
    b.append(f"Generated by `{ev['generated_by']}`. Command: `{ev['command']}`\n")
    b.append(f"- Decision points: **{ev['n_decision_points']:,}**, "
            f"conversations: **{ev['n_conversations']:,}**, tenants: **{ev['n_tenants']}**\n"
            f"- Window: {ev['window_ms']['since']} .. {ev['window_ms']['until']} (ms epoch)\n"
            f"- Train/test split: chronological, train_frac={ev['train_frac']}, "
            f"train_cut_ms={ev['train_cut_ms']}\n"
            f"- Bootstrap: {ev['bootstrap_reps']} reps, conversation-level resampling "
            f"(tenant, session, model) + id tiebreak, seed={ev['seed']}\n")
    mc = ev["multiple_comparisons"]
    b.append(f"\n## Multiple comparisons\n\n{mc['n_tests_raw']} tests run across "
            f"{len(ev['features'])} features x 3 outcomes; {mc['n_tests_with_a_pvalue']} "
            f"produced a usable p-value (the rest lacked enough data for that one outcome). "
            f"After {mc['method']} FDR correction at q<0.05, **{mc['n_survive_fdr_0.05']} of "
            f"{mc['n_tests_with_a_pvalue']}** survive. Raw and adjusted values are both in "
            f"`feature_evidence.json`; the table below states the outcome-c q-value inline "
            f"since it decides the verdict.\n")

    pe = ev.get("ping_everyone_vs_fixed_5m_reference", {})
    b.append("\n## The strawman every feature has to beat\n\n"
            f"Pinging every MIN_PREFIX-eligible decision point, no feature involved, "
            f"already beats fixed-5m by **{fmt_usd(pe.get('point_delta_usd'))}** "
            f"({pe.get('point_delta_pct', 0):.2f}%) on the held-out test window, 95% CI "
            f"[{fmt_usd((pe.get('ci95_delta_usd') or [None,None])[0])}, "
            f"{fmt_usd((pe.get('ci95_delta_usd') or [None,None])[1])}] -- because most gaps "
            f"close inside the ping schedule's own 280s interval (no ping ever fires, no "
            f"extra cost) while the rest get cheaply rescued.\n\n"
            f"**Every verdict below is decided against ping-everyone, not against "
            f"fixed-5m.** The fixed-5m comparison is reported alongside for continuity "
            f"with the rest of this study's own convention (every prior arm here was scored "
            f"against fixed-5m), but on its own it would make almost every feature look "
            f"like it 'HELPS' for a reason that has nothing to do with the feature.\n")

    b.append("\n## Every measured feature\n\n"
            "All numbers are **observed** (measured on the real snapshot; outcome (c)'s "
            "dollar figure is **replayed** -- a counterfactual re-simulation of the tested "
            "cost model, tuned on the train window and scored once on the held-out test "
            "window, never the other way round).\n")
    b.append("\n| Feature | Availability | N (missing) | $ vs fixed-5m, 95% CI (reference) | "
            "$ vs ping-everyone, 95% CI (decisive) | FDR q (outcome c) | Verdict |\n"
            "|---|---|---|---|---|---|---|")
    for f in ev["features"]:
        b.append(feature_row(f))
    b.append("")

    b.append("\n## Per-feature detail\n")
    for f in ev["features"]:
        b.append(f"\n### {f['catalogue_name']} (`{f['id']}`)\n")
        b.append(f"Family: {f['family']} | Availability: {f['availability']} | "
                f"Prior verdict (site catalogue): {f['prior_verdict']} | "
                f"**New verdict: {f['verdict']}** -- {f['verdict_reason']}\n")
        cov = f["coverage"]
        b.append(f"- Coverage: {cov['n_non_missing']:,}/{cov['n_decision_points']:,} decision "
                f"points ({cov['pct_missing']:.1f}% missing), "
                f"{cov['n_conversations_with_value']:,}/{cov['n_conversations']:,} "
                f"conversations, {cov['n_tenants_with_value']}/{cov['n_tenants']} tenants.")
        dist = f["distribution"]
        if dist.get("kind") == "numeric" and dist.get("n"):
            q = dist["quantiles"]
            b.append(f"- Distribution: p5={fmt_q(q.get('p5'))} p50={fmt_q(q.get('p50'))} "
                    f"p95={fmt_q(q.get('p95'))} p99={fmt_q(q.get('p99'))}"
                    f"{' (heavy tail)' if dist.get('heavy_tail') else ''}.")
        elif dist.get("kind") == "categorical":
            top = ", ".join(f"{c['category']} ({c['pct']:.1f}%)" for c in dist["top_categories"][:5])
            b.append(f"- Distribution: {dist['n_categories']} categories; top: {top}.")
        oc_a = f["outcomes"]["a_in_1h_or_earlier"]
        if f["kind"] == "numeric":
            auc = oc_a["auc"]
            ci = auc.get("ci95", [None, None])
            b.append(f"- Outcome (a) return-within-1h hazard: AUC={fmt_q(auc.get('auc'))} "
                    f"95% CI [{fmt_q(ci[0])}, {fmt_q(ci[1])}], raw p={fmt_q(oc_a.get('p_value'))}, "
                    f"FDR q={fmt_q((f.get('fdr') or {}).get('a_in_1h_or_earlier'))}.")
        else:
            hc = oc_a.get("headline_contrast")
            if hc:
                b.append(f"- Outcome (a): top-2-by-volume categories '{hc['a']}' "
                        f"({100*hc['rate_a']:.1f}%) vs '{hc['b']}' ({100*hc['rate_b']:.1f}%), "
                        f"risk ratio={fmt_q(hc.get('risk_ratio_a_over_b'))}, "
                        f"p={fmt_q(hc['p_value'])}, "
                        f"FDR q={fmt_q((f.get('fdr') or {}).get('a_in_1h_or_earlier'))}.")
        oc_b = f["outcomes"]["b_compatible_given_arrived"]
        if f["kind"] == "numeric":
            aucb = oc_b["auc"]
            b.append(f"- Outcome (b) prefix-compatible | arrived: AUC={fmt_q(aucb.get('auc'))}, "
                    f"FDR q={fmt_q((f.get('fdr') or {}).get('b_compatible_given_arrived'))}.")
        else:
            hcb = oc_b.get("headline_contrast")
            if hcb:
                b.append(f"- Outcome (b): '{hcb['a']}' ({100*hcb['rate_a']:.1f}% compatible) "
                        f"vs '{hcb['b']}' ({100*hcb['rate_b']:.1f}%), "
                        f"FDR q={fmt_q((f.get('fdr') or {}).get('b_compatible_given_arrived'))}.")
        c = f["outcomes"].get("c_dollar_value") or {}
        if c.get("point") is not None:
            ci = c["ci95"]
            f5 = c.get("vs_fixed_5m", {})
            ci5 = f5.get("ci95", [None, None])
            b.append(f"- Outcome (c): rule {c['rule']}, tuned on train, scored on test. "
                    f"**vs ping-everyone (decisive):** {fmt_usd(c['point'])}, 95% CI "
                    f"[{fmt_usd(ci[0])}, {fmt_usd(ci[1])}]. vs fixed-5m (reference): "
                    f"{fmt_usd(f5.get('point'))}, 95% CI [{fmt_usd(ci5[0])}, "
                    f"{fmt_usd(ci5[1])}]. n_test_conversations={c.get('n_conversations')}.")
        else:
            b.append(f"- Outcome (c): {c.get('reason', 'not enough data')}.")
        cf = f.get("confounding", {})
        b.append(f"- Confounding check, pooled effect vs. every stratifier "
                f"(stop_reason cluster, tenant, model, turn-index tercile, hour-of-day "
                f"bucket -- the brief's five, minus any that would be a tautology for this "
                f"feature): pooled={fmt_q(cf.get('pooled_effect'))}.")
        for strata_name, res in (cf.get("by_stratum") or {}).items():
            strata_txt = "; ".join(
                f"{s['stratum']}={'skip(n<50)' if s.get('skipped') else fmt_q(s.get('effect'))}"
                for s in res.get("strata", []))
            b.append(f"  - by {strata_name}: {strata_txt}")
        dis = cf.get("disagreement", {})
        if dis.get("disagrees"):
            flips_all = dis.get("flip_in", [])
            flips_big = [x for x in flips_all if x["n"] >= 500]
            flips_txt = "; ".join(f"{x['stratifier']}={x['stratum']} (n={x['n']}, "
                                  f"effect={fmt_q(x['effect'])})" for x in flips_all)
            big_txt = ("yes -- " + "; ".join(f"{x['stratifier']}={x['stratum']} (n={x['n']})"
                                             for x in flips_big)) if flips_big else "no large-n flip here"
            b.append(f"  - **disagreement heuristic fired**: range_ratio="
                    f"{fmt_q(dis.get('range_ratio'))} (>=2x the pooled effect's distance "
                    f"from null); sign flips in: {flips_txt if flips_txt else '(none, range only)'}. "
                    f"**This flag has no sample-size floor beyond the strata table's own "
                    f"min_n=50, so it fires on nearly every feature via small, noisy "
                    f"categories** (rare model-id variants, small tenants) -- read it as a "
                    f"screening signal, not a finding, unless the flip involves a stratum "
                    f"with n>=500: {big_txt}.")
        if f["id"] == "stop_reason":
            b.append("- **Idle-trigger confound: see the dedicated section right after "
                    "this table for the actual marginal-vs-conditional numbers.**")
        b.append(f"- Plot: `{plots_rel}/{f['id']}.svg`, caption: `{plots_rel}/{f['id']}.txt`.")

    stop_f = next((f for f in ev["features"] if f["id"] == "stop_reason"), None)
    if stop_f and stop_f.get("confounding_idle_ge_280s"):
        trig = stop_f["confounding_idle_ge_280s"]
        m = {r["category"]: r for r in trig["marginal_rates"]}
        c = {r["category"]: r for r in trig["conditional_on_idle_ge_280s_rates"]}
        b.append("\n## stop_reason's idle-trigger confound -- the actual numbers\n")
        b.append("The brief's central trap, checked directly rather than assumed: "
                "does stop_reason's marginal signal survive once you restrict to decision "
                f"points that already reached the production ping trigger's own "
                f"{trig['idle_trigger_ms']/1000:.0f}-second idle delay?\n")
        b.append("\n| stop_reason | marginal N | marginal rate | conditional N (idle>=280s) | "
                "conditional rate |\n|---|---|---|---|---|")
        for cat in sorted(m, key=lambda k: -m[k]["n"]):
            mr, cr = m[cat], c.get(cat)
            crate = f"{cr['rate']*100:.2f}%" if cr and cr["n"] else "n/a (0 rows)"
            b.append(f"| {cat} | {mr['n']:,} | {mr['rate']*100:.2f}% | "
                    f"{cr['n']:,} | {crate} |" if cr else
                    f"| {cat} | {mr['n']:,} | {mr['rate']*100:.2f}% | 0 | n/a |")
        big3 = ["tool_use", "stop_sequence", "end_turn"]
        m_big = [m[k]["rate"] * 100 for k in big3 if k in m]
        c_big = [c[k]["rate"] * 100 for k in big3 if k in c and c[k]["n"]]
        m_spread = max(m_big) - min(m_big) if len(m_big) == 3 else None
        c_spread = max(c_big) - min(c_big) if len(c_big) == 3 else None
        m_str = "/".join(f"{m[k]['rate']*100:.1f}" for k in big3 if k in m)
        c_str = "/".join(f"{c[k]['rate']*100:.1f}" for k in big3 if k in c and c[k]["n"])
        stop_m = m.get("stop", {}).get("rate")
        stop_c = c.get("stop", {}).get("rate")
        b.append(f"\n**What this actually shows, measured with proper censoring (a "
                f"trigger-reaching span that never got a successor counts as a non-return, "
                f"not an exclusion -- the first cut of this table dropped 15,409 of 23,800 "
                f"true trigger-reaching decision points, all of them exactly the never-"
                f"returned failures the conditional rate needs, which inflated it): the "
                f"ranking among the three big clusters survives (tool_use > stop_sequence "
                f"> end_turn, both marginally and conditionally), and the point-spread "
                f"among them is NOT smaller conditionally ({c_str}%, a "
                f"~{c_spread:.1f}-point spread) than marginally ({m_str}%, a "
                f"~{m_spread:.1f}-point spread) -- if anything it is roughly "
                f"{c_spread/m_spread:.1f}x wider. So stop_reason's own discriminative "
                f"signal does NOT evaporate once conditioned on the trigger, which is a "
                f"more precise finding than 'redundant with the trigger.'**\n\n"
                f"**A new finding this correction surfaced: the 'stop' category "
                f"(stop_cluster='looks_done_isnt') is a near-total dead end** -- "
                f"{100*stop_m:.2f}% marginal, and once conditioned on the trigger, "
                f"**{100*stop_c:.3f}%** (essentially zero; {c.get('stop',{}).get('n',0):,} "
                f"trigger-reaching decision points, {c.get('stop',{}).get('k',0)} rescued). "
                f"Unlike tool_use/stop_sequence/end_turn, excluding 'stop' from a ping "
                f"policy costs almost nothing -- this is the one cluster stop_reason "
                f"correctly flags as safe to gate away.\n\n"
                f"**The actual mechanism behind outcome (c)'s HARMS AS A GATE verdict "
                f"is under-coverage of the OTHER clusters, not a lack of signal: the "
                f"shipped/studied stop-reason-gated policy pings only 'end_turn' "
                f"(actually_done), whose conditional rescue rate ({c.get('end_turn',{}).get('rate',0)*100:.1f}%) "
                f"is actually the LOWEST of the three substantial clusters -- it excludes "
                f"tool_use ({c.get('tool_use',{}).get('rate',0)*100:.1f}%) and "
                f"stop_sequence ({c.get('stop_sequence',{}).get('rate',0)*100:.1f}%), both "
                f"higher-value, from the ping policy entirely. stop_reason ranks the "
                f"clusters correctly (including correctly flagging 'stop' as worthless); "
                f"the harm comes from which clusters the SHIPPED single-category gate "
                f"chooses to include and exclude, not from a lack of signal. Whether a "
                f"smarter rule (e.g. 'ping everyone except stop') would beat ping-everyone "
                f"was NOT tested in this sweep -- this script's outcome-(c) grid only "
                f"tries single-category 'ping only on X' rules, matching the established "
                f"literature's own gate definition, not exclusion rules -- and is flagged "
                f"here as a concrete, promising follow-up rather than claimed as tested.**\n")

    ti = ev.get("tenant_identity")
    if ti:
        b.append("\n## Tenant identity (confound context, not a catalogue row)\n")
        if ti.get("correction_note"):
            b.append(f"\n> **Correction applied:** {ti['correction_note']}\n")
        rows_t = ti.get("per_tenant_trigger_conditional_rescue_rate", [])
        rates = [r["rescue_rate_pct"] for r in rows_t if r["rescue_rate_pct"] is not None]
        n_clear = ti.get("n_tenants_clearing_break_even_trigger_conditional")
        b.append(f"**Trigger-conditional rescue rate** (population: decision points that "
                f"reached the 280s ping trigger -- gap "
                f"observed >=280s, OR censored with elapsed-to-window-end >=280s -- scored "
                f"against whether a successor arrived within {ti.get('rescue_horizon_ms', 880000)/1000:.0f}s, "
                f"proper censoring: a trigger-reaching span that never got a successor "
                f"counts as a non-rescue, not an exclusion): ranges from "
                f"{min(rates):.1f}% to {max(rates):.1f}% across {len(rows_t)} tenants "
                f"(n>=30). Break-even is **{ti['break_even_pct']:.2f}%** (r/(w-r)). "
                f"**{n_clear} of {len(rates)} tenants clear it**"
                f"{', comfortably (several by 4-5x)' if n_clear and n_clear >= len(rates)-1 else ''}. "
                f"Verdict (from the full cost-model replay below, which is the decisive "
                f"one): **{ti['verdict']}** -- {ti['verdict_reason']}\n")
        b.append("\n| Tenant | N (trigger-reaching, full window) | Rescue rate (within "
                f"{ti.get('rescue_horizon_ms', 880000)/1000:.0f}s of trigger) |\n|---|---|---|")
        for r in rows_t:
            rr = r["rescue_rate_pct"]
            b.append(f"| {r['tenant']} | {r['n']:,} | "
                    f"{f'{rr:.1f}%' if rr is not None else 'n/a'} |")

        b.append("\n**Full cost-model replay, the decisive comparison:** the "
                "trigger-conditional rate above answers 'is this tenant's rescue rate "
                "above the myopic break-even', which is a necessary check but not "
                "sufficient on its own (it says nothing about whether restricting the "
                "*policy* to just this tenant beats the alternatives). Whether 'ping "
                "whenever tenant==X' actually makes or loses money is therefore also run "
                "through the same full replay as every other outcome-(c) test here, per "
                "tenant, on the held-out test window:\n")
        b.append("\n| Tenant | N (test) | vs fixed-5m, 95% CI | vs ping-everyone, 95% CI |\n"
                "|---|---|---|---|")
        for d in ti.get("per_tenant_ping_dollar_value", []):
            if d.get("skipped"):
                b.append(f"| {d['tenant']} | {d['n']:,} | skipped (n<200) | skipped |")
                continue
            c5 = d["vs_fixed_5m_ci95"]
            cp = d["vs_ping_everyone_ci95"]
            b.append(f"| {d['tenant']} | {d['n']:,} | "
                    f"{fmt_usd(d['vs_fixed_5m_usd'])} [{fmt_usd(c5[0])}, {fmt_usd(c5[1])}] | "
                    f"{fmt_usd(d['vs_ping_everyone_usd'])} [{fmt_usd(cp[0])}, {fmt_usd(cp[1])}] |")
        b.append(f"\n**Any tenant beats fixed-5m (CI excludes 0): "
                f"{ti.get('any_tenant_beats_fixed_5m')}.** "
                f"**Any tenant beats ping-everyone (CI excludes 0): "
                f"{ti.get('any_tenant_beats_ping_everyone')}.** "
                f"If the first is True, that measured result **overturns** the myopic "
                f"break-even's implication that gating on tenant identity alone loses "
                f"money for every tenant -- reported exactly as measured either way, not "
                f"adjusted to match the expectation stated when this table was requested.\n")

        b.append("\nNot part of the 18-feature BH-FDR pool above (tenant identity is not "
                "one of the catalogue's 38 rows -- it is the confound behind every one of "
                "them, reported here because it is the single strongest univariate split "
                "in the corpus).\n")

    b.append("\n## Features that resolve to another measurement (aliases)\n")
    for a in ev["aliases"]:
        b.append(f"- **{a['catalogue_name']}** -> see `{a['alias_of']}` above. {a['note']}")

    b.append("\n## Not usable as a feature (measured for coverage only)\n")
    na = ev["not_a_feature"]
    d = na.get("distribution", {})
    b.append(f"- **{na['catalogue_name']}**: {na['reason']} Coverage: "
            f"{na.get('coverage', {}).get('n_decision_points', 0):,} decision points. "
            f"Distribution (descriptive only): mean={fmt_q(d.get('mean'))}, "
            f"p50={fmt_q((d.get('quantiles') or {}).get('p50'))}, "
            f"p99={fmt_q((d.get('quantiles') or {}).get('p99'))}, "
            f"{fmt_q(d.get('pct_zero'))}% zero.")

    b.append("\n## Excluded on privacy grounds\n")
    for p in ev["privacy_excluded"]:
        b.append(f"- **{p['catalogue_name']}**: {p['reason']}")

    b.append("\n## Absent (do not exist; not silently dropped)\n")
    b.append("\n| Feature | Class | Why |\n|---|---|---|")
    for a in ev["absent"]:
        b.append(f"| {a['catalogue_name']} | {a['availability']} | {a['reason']} |")

    b.append("\n## What I could not measure, and why\n")
    b.append("- **Text cues in the last message** -- privacy exclusion, stated above; this "
            "sweep never reads `request_content`'s text.\n"
            "- **Count of subsequent compatible requests** -- structurally a forward-looking "
            "label, not a backwards-safe feature; measured for coverage/distribution only, "
            "never scored against an outcome (see the 'not usable as a feature' section).\n"
            "- **14 catalogued rows across subagents, per-call tool timing, agent phase, "
            "task outcome, tenant-local time, and workspace identity** do not exist in the "
            "schema at all (see the absent table); no amount of measurement recovers them.\n"
            "- What IS run for every one of the 18 measured features, without exception: "
            "full stratification by stop_reason cluster, tenant, model, turn-index tercile "
            "and hour-of-day bucket (the brief's five), with a pooled-vs-per-stratum "
            "disagreement check. What is NOT run: a joint (tenant x model x hour) cross-"
            "tabulation, or a formal test of whether each individual stratum's effect "
            "differs from the pooled one with its own multiple-comparison correction -- "
            "the disagreement flag is a screening heuristic (stated inline per feature), "
            "not a second FDR-controlled analysis.\n"
            "- The `a_in_5m` outcome (P(returns within exactly 5 minutes), as distinct from "
            "the `a_in_1h_or_earlier` outcome detailed per feature above) is measured and "
            "included in the 72-test FDR pool, but not narrated per feature above -- see "
            "`feature_evidence.json`'s `outcomes.a_in_5m` for each feature's full numbers.\n")
    return "\n".join(b) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in-json", required=True)
    ap.add_argument("--plots-rel", default="../exp3/features/plots")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    ev = json.loads(Path(args.in_json).read_text())
    Path(args.out).write_text(build(ev, args.plots_rel))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
