#!/usr/bin/env python3
"""Render exp3/features/feature_evidence.json into reports3/feat-univariate.md.

Reads only the JSON kv_ttl_feature_univariate.py already wrote -- never touches the DB, so
this can be re-run (or handed to someone else) without re-measuring anything.

Usage:
    python3 kv_ttl_featureuni_report.py --in-json .../feature_evidence.json \
        --plots-rel plots --out .../feat-univariate.md
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def fmt_usd(v) -> str:
    if v is None:
        return "n/a"
    return f"${v:,.2f}"


def fmt_q(v) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "n/a"
    return f"{v:.3g}"


def feature_row(f: dict) -> str:
    cov = f["coverage"]
    c = f["outcomes"].get("c_dollar_value") or {}
    q_c = (f.get("fdr") or {}).get("c_dollar_value")
    ci = c.get("ci95", [None, None])
    f5 = c.get("vs_fixed_5m", {})
    ci5 = f5.get("ci95", [None, None])
    return (f"| {f['catalogue_name']} | {f['availability']} | "
           f"{cov['n_non_missing']:,} ({cov['pct_missing']:.1f}% missing) | "
           f"{fmt_usd(f5.get('point'))} [{fmt_usd(ci5[0])}, {fmt_usd(ci5[1])}] | "
           f"{fmt_usd(c.get('point'))} [{fmt_usd(ci[0])}, {fmt_usd(ci[1])}] | "
           f"{fmt_q(q_c)} | **{f['verdict']}** |")


def build(ev: dict, plots_rel: str) -> str:
    b = []
    b.append("# Feature univariate evidence\n")
    b.append(f"Generated by `{ev['generated_by']}`. Command: `{ev['command']}`\n")
    b.append(f"- Decision points: **{ev['n_decision_points']:,}**, "
            f"conversations: **{ev['n_conversations']:,}**, tenants: **{ev['n_tenants']}**\n"
            f"- Window: {ev['window_ms']['since']} .. {ev['window_ms']['until']} (ms epoch)\n"
            f"- Train/test split: chronological, train_frac={ev['train_frac']}, "
            f"train_cut_ms={ev['train_cut_ms']}\n"
            f"- Bootstrap: {ev['bootstrap_reps']} reps, conversation-level resampling "
            f"(tenant, session, model) + id tiebreak, seed={ev['seed']}\n")
    mc = ev["multiple_comparisons"]
    b.append(f"\n## Multiple comparisons\n\n{mc['n_tests_raw']} tests run across "
            f"{len(ev['features'])} features x 3 outcomes; {mc['n_tests_with_a_pvalue']} "
            f"produced a usable p-value (the rest lacked enough data for that one outcome). "
            f"After {mc['method']} FDR correction at q<0.05, **{mc['n_survive_fdr_0.05']} of "
            f"{mc['n_tests_with_a_pvalue']}** survive. Raw and adjusted values are both in "
            f"`feature_evidence.json`; the table below states the outcome-c q-value inline "
            f"since it decides the verdict.\n")

    pe = ev.get("ping_everyone_vs_fixed_5m_reference", {})
    b.append("\n## The strawman every feature has to beat\n\n"
            f"Pinging every MIN_PREFIX-eligible decision point, no feature involved, "
            f"already beats fixed-5m by **{fmt_usd(pe.get('point_delta_usd'))}** "
            f"({pe.get('point_delta_pct', 0):.2f}%) on the held-out test window, 95% CI "
            f"[{fmt_usd((pe.get('ci95_delta_usd') or [None,None])[0])}, "
            f"{fmt_usd((pe.get('ci95_delta_usd') or [None,None])[1])}] -- because most gaps "
            f"close inside the ping schedule's own 280s interval (no ping ever fires, no "
            f"extra cost) while the rest get cheaply rescued.\n\n"
            f"**Every verdict below is decided against ping-everyone, not against "
            f"fixed-5m.** The fixed-5m comparison is reported alongside for continuity "
            f"with the rest of this study's own convention (every prior arm here was scored "
            f"against fixed-5m), but on its own it would make almost every feature look "
            f"like it 'HELPS' for a reason that has nothing to do with the feature.\n")

    b.append("\n## Every measured feature\n\n"
            "All numbers are **observed** (measured on the real snapshot; outcome (c)'s "
            "dollar figure is **replayed** -- a counterfactual re-simulation of the tested "
            "cost model, tuned on the train window and scored once on the held-out test "
            "window, never the other way round).\n")
    b.append("\n| Feature | Availability | N (missing) | $ vs fixed-5m, 95% CI (reference) | "
            "$ vs ping-everyone, 95% CI (decisive) | FDR q (outcome c) | Verdict |\n"
            "|---|---|---|---|---|---|---|")
    for f in ev["features"]:
        b.append(feature_row(f))
    b.append("")

    b.append("\n## Per-feature detail\n")
    for f in ev["features"]:
        b.append(f"\n### {f['catalogue_name']} (`{f['id']}`)\n")
        b.append(f"Family: {f['family']} | Availability: {f['availability']} | "
                f"Prior verdict (site catalogue): {f['prior_verdict']} | "
                f"**New verdict: {f['verdict']}** -- {f['verdict_reason']}\n")
        cov = f["coverage"]
        b.append(f"- Coverage: {cov['n_non_missing']:,}/{cov['n_decision_points']:,} decision "
                f"points ({cov['pct_missing']:.1f}% missing), "
                f"{cov['n_conversations_with_value']:,}/{cov['n_conversations']:,} "
                f"conversations, {cov['n_tenants_with_value']}/{cov['n_tenants']} tenants.")
        dist = f["distribution"]
        if dist.get("kind") == "numeric" and dist.get("n"):
            q = dist["quantiles"]
            b.append(f"- Distribution: p5={fmt_q(q.get('p5'))} p50={fmt_q(q.get('p50'))} "
                    f"p95={fmt_q(q.get('p95'))} p99={fmt_q(q.get('p99'))}"
                    f"{' (heavy tail)' if dist.get('heavy_tail') else ''}.")
        elif dist.get("kind") == "categorical":
            top = ", ".join(f"{c['category']} ({c['pct']:.1f}%)" for c in dist["top_categories"][:5])
            b.append(f"- Distribution: {dist['n_categories']} categories; top: {top}.")
        oc_a = f["outcomes"]["a_in_1h_or_earlier"]
        if f["kind"] == "numeric":
            auc = oc_a["auc"]
            ci = auc.get("ci95", [None, None])
            b.append(f"- Outcome (a) return-within-1h hazard: AUC={fmt_q(auc.get('auc'))} "
                    f"95% CI [{fmt_q(ci[0])}, {fmt_q(ci[1])}], raw p={fmt_q(oc_a.get('p_value'))}, "
                    f"FDR q={fmt_q((f.get('fdr') or {}).get('a_in_1h_or_earlier'))}.")
        else:
            hc = oc_a.get("headline_contrast")
            if hc:
                b.append(f"- Outcome (a): top-2-by-volume categories '{hc['a']}' "
                        f"({100*hc['rate_a']:.1f}%) vs '{hc['b']}' ({100*hc['rate_b']:.1f}%), "
                        f"risk ratio={fmt_q(hc.get('risk_ratio_a_over_b'))}, "
                        f"p={fmt_q(hc['p_value'])}, "
                        f"FDR q={fmt_q((f.get('fdr') or {}).get('a_in_1h_or_earlier'))}.")
        oc_b = f["outcomes"]["b_compatible_given_arrived"]
        if f["kind"] == "numeric":
            aucb = oc_b["auc"]
            b.append(f"- Outcome (b) prefix-compatible | arrived: AUC={fmt_q(aucb.get('auc'))}, "
                    f"FDR q={fmt_q((f.get('fdr') or {}).get('b_compatible_given_arrived'))}.")
        else:
            hcb = oc_b.get("headline_contrast")
            if hcb:
                b.append(f"- Outcome (b): '{hcb['a']}' ({100*hcb['rate_a']:.1f}% compatible) "
                        f"vs '{hcb['b']}' ({100*hcb['rate_b']:.1f}%), "
                        f"FDR q={fmt_q((f.get('fdr') or {}).get('b_compatible_given_arrived'))}.")
        c = f["outcomes"].get("c_dollar_value") or {}
        if c.get("point") is not None:
            ci = c["ci95"]
            f5 = c.get("vs_fixed_5m", {})
            ci5 = f5.get("ci95", [None, None])
            b.append(f"- Outcome (c): rule {c['rule']}, tuned on train, scored on test. "
                    f"**vs ping-everyone (decisive):** {fmt_usd(c['point'])}, 95% CI "
                    f"[{fmt_usd(ci[0])}, {fmt_usd(ci[1])}]. vs fixed-5m (reference): "
                    f"{fmt_usd(f5.get('point'))}, 95% CI [{fmt_usd(ci5[0])}, "
                    f"{fmt_usd(ci5[1])}]. n_test_conversations={c.get('n_conversations')}.")
        else:
            b.append(f"- Outcome (c): {c.get('reason', 'not enough data')}.")
        cf = f.get("confounding", {})
        b.append(f"- Confounding check, pooled effect vs. every stratifier "
                f"(stop_reason cluster, tenant, model, turn-index tercile, hour-of-day "
                f"bucket -- the brief's five, minus any that would be a tautology for this "
                f"feature): pooled={fmt_q(cf.get('pooled_effect'))}.")
        for strata_name, res in (cf.get("by_stratum") or {}).items():
            strata_txt = "; ".join(
                f"{s['stratum']}={'skip(n<50)' if s.get('skipped') else fmt_q(s.get('effect'))}"
                for s in res.get("strata", []))
            b.append(f"  - by {strata_name}: {strata_txt}")
        dis = cf.get("disagreement", {})
        if dis.get("disagrees"):
            flips_all = dis.get("flip_in", [])
            flips_big = [x for x in flips_all if x["n"] >= 500]
            flips_txt = "; ".join(f"{x['stratifier']}={x['stratum']} (n={x['n']}, "
                                  f"effect={fmt_q(x['effect'])})" for x in flips_all)
            big_txt = ("yes -- " + "; ".join(f"{x['stratifier']}={x['stratum']} (n={x['n']})"
                                             for x in flips_big)) if flips_big else "no large-n flip here"
            b.append(f"  - **disagreement heuristic fired**: range_ratio="
                    f"{fmt_q(dis.get('range_ratio'))} (>=2x the pooled effect's distance "
                    f"from null); sign flips in: {flips_txt if flips_txt else '(none, range only)'}. "
                    f"**This flag has no sample-size floor beyond the strata table's own "
                    f"min_n=50, so it fires on nearly every feature via small, noisy "
                    f"categories** (rare model-id variants, small tenants) -- read it as a "
                    f"screening signal, not a finding, unless the flip involves a stratum "
                    f"with n>=500: {big_txt}.")
        if f["id"] == "stop_reason":
            b.append("- **Idle-trigger confound: see the dedicated section right after "
                    "this table for the actual marginal-vs-conditional numbers.**")
        b.append(f"- Plot: `{plots_rel}/{f['id']}.svg`, caption: `{plots_rel}/{f['id']}.txt`.")

    stop_f = next((f for f in ev["features"] if f["id"] == "stop_reason"), None)
    if stop_f and stop_f.get("confounding_idle_ge_280s"):
        trig = stop_f["confounding_idle_ge_280s"]
        m = {r["category"]: r for r in trig["marginal_rates"]}
        c = {r["category"]: r for r in trig["conditional_on_idle_ge_280s_rates"]}
        b.append("\n## stop_reason's idle-trigger confound -- the actual numbers\n")
        b.append("The brief's central trap, checked directly rather than assumed: "
                "does stop_reason's marginal signal survive once you restrict to decision "
                f"points that already reached the production ping trigger's own "
                f"{trig['idle_trigger_ms']/1000:.0f}-second idle delay?\n")
        b.append("\n| stop_reason | marginal N | marginal rate | conditional N (idle>=280s) | "
                "conditional rate |\n|---|---|---|---|---|")
        for cat in sorted(m, key=lambda k: -m[k]["n"]):
            mr, cr = m[cat], c.get(cat)
            crate = f"{cr['rate']*100:.2f}%" if cr and cr["n"] else "n/a (0 rows)"
            b.append(f"| {cat} | {mr['n']:,} | {mr['rate']*100:.2f}% | "
                    f"{cr['n']:,} | {crate} |" if cr else
                    f"| {cat} | {mr['n']:,} | {mr['rate']*100:.2f}% | 0 | n/a |")
        b.append("\n**What this actually shows, measured rather than assumed: the ranking "
                "survives (tool_use > stop_sequence > end_turn, both marginally and "
                "conditionally), and the absolute point-spread among the three big "
                "clusters is not smaller conditionally (87.2/81.9/77.5%, a ~9.7-point "
                "spread) than marginally (99.9/99.3/96.7%, a ~3.2-point spread) -- if "
                "anything it's wider. So stop_reason's own discriminative signal does "
                "NOT simply evaporate once you condition on the trigger, which is a "
                "more precise finding than 'redundant with the trigger.'**\n\n"
                "**The actual mechanism behind outcome (c)'s HARMS AS A GATE verdict "
                "(measured above: gating on end_turn alone costs $249 vs. ping-everyone) "
                "is under-coverage, not a lack of signal: every cluster's CONDITIONAL "
                "return-within-1h rate is still high (57-92% once a decision point has "
                "already gone idle 280s+), so excluding any cluster from the ping policy "
                "forgoes real, still-substantial rescue value on it. stop_reason ranks "
                "the clusters correctly; it just doesn't identify any cluster worth "
                "excluding once you're already past the trigger.**\n")

    ti = ev.get("tenant_identity")
    if ti:
        b.append("\n## Tenant identity (confound context, not a catalogue row)\n")
        rows_t = ti.get("per_tenant_band_rate", [])
        rates = [r["band_rate_pct"] for r in rows_t]
        spread = (max(rates) / min([r for r in rates if r > 0], default=1)) if rates else None
        b.append(f"Measured directly (full window, tenants with n>=1,000, pseudonyms only): "
                f"rescue-band rate ranges from {min(rates):.2f}% to {max(rates):.2f}% "
                f"across {len(rows_t)} tenants"
                f"{f' (a {spread:.0f}x spread)' if spread else ''}. Break-even for an "
                f"unconditional ping is **{ti['break_even_pct']:.2f}%** (r/(w-r), the "
                f"marginal cost of a write over a read). "
                f"**{'A tenant clears it' if ti['any_tenant_clears_break_even'] else 'No tenant clears it'}** "
                f"-- the best is {ti['max_tenant_band_rate_pct']:.2f}%. Verdict: "
                f"**{ti['verdict']}** -- {ti['verdict_reason']}\n")
        b.append("\n| Tenant | N (eligible, full window) | Rescue-band rate |\n|---|---|---|")
        for r in rows_t:
            b.append(f"| {r['tenant']} | {r['n']:,} | {r['band_rate_pct']:.2f}% |")

        b.append("\n**Direct test, not inherited from the myopic break-even formula:** "
                "the band-rate-vs-8.70% comparison above is the simple r/(w-r) heuristic. "
                "Whether 'ping whenever tenant==X' actually loses money is a full "
                "cost-model question (PingSchedule only pays for a ping when idle time "
                "actually crosses its interval, which is why the ping-everyone reference "
                "elsewhere in this report beats fixed-5m despite a 2.6% base rate well "
                "under the myopic bar) -- so it was run through the same replay as every "
                "other outcome-(c) test here, per tenant, on the held-out test window:\n")
        b.append("\n| Tenant | N (test) | vs fixed-5m, 95% CI | vs ping-everyone, 95% CI |\n"
                "|---|---|---|---|")
        for d in ti.get("per_tenant_ping_dollar_value", []):
            if d.get("skipped"):
                b.append(f"| {d['tenant']} | {d['n']:,} | skipped (n<200) | skipped |")
                continue
            c5 = d["vs_fixed_5m_ci95"]
            cp = d["vs_ping_everyone_ci95"]
            b.append(f"| {d['tenant']} | {d['n']:,} | "
                    f"{fmt_usd(d['vs_fixed_5m_usd'])} [{fmt_usd(c5[0])}, {fmt_usd(c5[1])}] | "
                    f"{fmt_usd(d['vs_ping_everyone_usd'])} [{fmt_usd(cp[0])}, {fmt_usd(cp[1])}] |")
        b.append(f"\n**Any tenant beats fixed-5m (CI excludes 0): "
                f"{ti.get('any_tenant_beats_fixed_5m')}.** "
                f"**Any tenant beats ping-everyone (CI excludes 0): "
                f"{ti.get('any_tenant_beats_ping_everyone')}.** "
                f"If the first is True, that measured result **overturns** the myopic "
                f"break-even's implication that gating on tenant identity alone loses "
                f"money for every tenant -- reported exactly as measured either way, not "
                f"adjusted to match the expectation stated when this table was requested.\n")

        b.append("\nNot part of the 18-feature BH-FDR pool above (tenant identity is not "
                "one of the catalogue's 38 rows -- it is the confound behind every one of "
                "them, reported here because it is the single strongest univariate split "
                "in the corpus).\n")

    b.append("\n## Features that resolve to another measurement (aliases)\n")
    for a in ev["aliases"]:
        b.append(f"- **{a['catalogue_name']}** -> see `{a['alias_of']}` above. {a['note']}")

    b.append("\n## Not usable as a feature (measured for coverage only)\n")
    na = ev["not_a_feature"]
    d = na.get("distribution", {})
    b.append(f"- **{na['catalogue_name']}**: {na['reason']} Coverage: "
            f"{na.get('coverage', {}).get('n_decision_points', 0):,} decision points. "
            f"Distribution (descriptive only): mean={fmt_q(d.get('mean'))}, "
            f"p50={fmt_q((d.get('quantiles') or {}).get('p50'))}, "
            f"p99={fmt_q((d.get('quantiles') or {}).get('p99'))}, "
            f"{fmt_q(d.get('pct_zero'))}% zero.")

    b.append("\n## Excluded on privacy grounds\n")
    for p in ev["privacy_excluded"]:
        b.append(f"- **{p['catalogue_name']}**: {p['reason']}")

    b.append("\n## Absent (do not exist; not silently dropped)\n")
    b.append("\n| Feature | Class | Why |\n|---|---|---|")
    for a in ev["absent"]:
        b.append(f"| {a['catalogue_name']} | {a['availability']} | {a['reason']} |")

    b.append("\n## What I could not measure, and why\n")
    b.append("- **Text cues in the last message** -- privacy exclusion, stated above; this "
            "sweep never reads `request_content`'s text.\n"
            "- **Count of subsequent compatible requests** -- structurally a forward-looking "
            "label, not a backwards-safe feature; measured for coverage/distribution only, "
            "never scored against an outcome (see the 'not usable as a feature' section).\n"
            "- **14 catalogued rows across subagents, per-call tool timing, agent phase, "
            "task outcome, tenant-local time, and workspace identity** do not exist in the "
            "schema at all (see the absent table); no amount of measurement recovers them.\n"
            "- What IS run for every one of the 18 measured features, without exception: "
            "full stratification by stop_reason cluster, tenant, model, turn-index tercile "
            "and hour-of-day bucket (the brief's five), with a pooled-vs-per-stratum "
            "disagreement check. What is NOT run: a joint (tenant x model x hour) cross-"
            "tabulation, or a formal test of whether each individual stratum's effect "
            "differs from the pooled one with its own multiple-comparison correction -- "
            "the disagreement flag is a screening heuristic (stated inline per feature), "
            "not a second FDR-controlled analysis.\n"
            "- The `a_in_5m` outcome (P(returns within exactly 5 minutes), as distinct from "
            "the `a_in_1h_or_earlier` outcome detailed per feature above) is measured and "
            "included in the 72-test FDR pool, but not narrated per feature above -- see "
            "`feature_evidence.json`'s `outcomes.a_in_5m` for each feature's full numbers.\n")
    return "\n".join(b) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in-json", required=True)
    ap.add_argument("--plots-rel", default="../exp3/features/plots")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    ev = json.loads(Path(args.in_json).read_text())
    Path(args.out).write_text(build(ev, args.plots_rel))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
