// Code generated by deploy/harbor/kv_ttl_keepalive_policy.py --go-out. DO NOT EDIT.
//
// Regenerate with:
//
//	cd deploy/harbor && python3 kv_ttl_keepalive_policy.py \
//	    --db /var/lib/context-guru/cg.db --prices /etc/context-guru/prices.yaml \
//	    --model-out reusemodel_v1.json --go-out ../../kvcache/reusemodel_v1_gen.go
//
// Provenance. This is the argument for trusting the coefficients, so it is generated
// from the fit rather than written by hand — including the parts that are unflattering.
//
//	window (UTC)        2026-08-17 11:48 -> 2026-09-04 21:45 UTC  (18.4 days)
//	requests            219650
//	idle spans          219650
//	  reaching sweep 1  37418   <- the population the decision is actually faced on
//	person-periods      276321
//	schedule            interval 280s / life 300s / max_k 8
//	survived to sweep+1 98.53% of person-periods
//
//	fit weight          stake
//
//	                    AUC by row   AUC by dollar   logloss   mean p / actual
//	holdout (late 30%)  0.9065       0.7837          0.0345      0.9868 / 0.9919
//	in-sample           0.8855       0.7597          0.0573      0.9826 / 0.9853
//	in-sample, ref GBM  0.9572       0.8705          0.0503      0.9776 / 0.9853
//
// The HOLDOUT row is the one to argue with: it is fitted on the early 70% of the
// window and scored on the late 30%, split by time rather than at random because one
// span contributes up to max_k person-periods and a random split scores a row against
// its own siblings. The in-sample rows are here only to show the gap; the reference
// GBM's in-sample figures in particular are an upper bound on nothing.
//
// Neither AUC is a saving. What this arm is worth in money is the KV-cache page's own
// replay of a window under it, against the same baseline as every other arm — which is
// what shipping it as a registry arm is for. docs/how-to/kv-cache-keepalive-budget.md
// carries the measured table and says plainly where a flat MaxPings still beats it.

package kvcache

// ReuseModelV1 is the fitted, frozen reuse model the `keepalive-budget` arm reads.
//
// See reusemodel.go for what the fields mean and for the CDF this composes. The
// numbers are a logistic survival fit on the corpus named above; the Python that
// produced them, the feature arithmetic they assume, and this table are pinned
// together by TestReuseModelV1AgreesWithThePort.
var ReuseModelV1 = &ReuseModel{
	Version:   "v1",
	TrainedOn: "2026-08-17 11:48 -> 2026-09-04 21:45 UTC",
	IntervalS: 280.0,
	LifeS:     300.0,
	MaxK:      8,
	Intercept: 5.018342744954828,
	Numeric: []ReuseTerm{
		{Name: "log_prefix", Coef: -2.0617767376699336, Center: 4.146090828434305, Scale: 4.7037498066187835},
		{Name: "log_prev_gap", Coef: -0.051073693614662456, Center: 0.8069032678784968, Scale: 1.7739566028829084},
		{Name: "turn", Coef: 0.17222201868549095, Center: 93.21953452687274, Scale: 539.4799156608967},
		{Name: "hour_sin", Coef: -0.11807319204324197, Center: -0.03876981083782035, Scale: 0.698196684692585},
		{Name: "hour_cos", Coef: 0.05351815398273302, Center: -0.12480005679454068, Scale: 0.7038772883647778},
		{Name: "dow_sin", Coef: -0.044776344705750655, Center: 0.5289808564926407, Scale: 0.5991648136759256},
		{Name: "dow_cos", Coef: 0.06955802004724103, Center: -0.27736442403982214, Scale: 0.5331507814789217},
		{Name: "stat_p", Coef: 0.3068298285865256, Center: 0.8669557007725781, Scale: 0.13350760774270665},
		{Name: "log_stat_n", Coef: -0.028663327452458465, Center: 5.707126141180795, Scale: 1.7859544188184382},
	},
	Categorical: []ReuseCategory{
		{Name: "model", Levels: []ReuseLevel{
			{Level: "", Coef: 0.044073416904029585},
			{Level: "aws/claude-haiku-4-5", Coef: 0.01059219829200029},
			{Level: "aws/claude-opus-5", Coef: 0.5891045430667132},
			{Level: "aws/claude-sonnet-5", Coef: 0.4672028093860629},
			{Level: "azure/gpt-4o", Coef: 0.04754489687167924},
			{Level: "azure/gpt-5.5", Coef: 0.43532292998608124},
			{Level: "claude-haiku-4-5", Coef: 0.05693310295387887},
			{Level: "claude-opus-4-6", Coef: 0.8914374258675521},
			{Level: "claude-opus-4-7", Coef: 0.20280481953179896},
			{Level: "claude-opus-4-8", Coef: 0.5671313782762598},
			{Level: "claude-opus-5", Coef: 0.759769916393038},
			{Level: "claude-sonnet-4-6", Coef: 0.6687443839651331},
			{Level: "claude-sonnet-5", Coef: 0.24100295418844414},
		}},
		{Name: "sweep", Levels: []ReuseLevel{
			{Level: "", Coef: 0.0},
			{Level: "1", Coef: -0.8103139873353238},
			{Level: "2", Coef: -0.04573723713715996},
			{Level: "3", Coef: 0.6255276686681279},
			{Level: "4", Coef: 0.8279466337110583},
			{Level: "5", Coef: 0.35705180846007445},
			{Level: "6", Coef: 0.6740656989771248},
			{Level: "7", Coef: 1.8645461417180886},
			{Level: "8", Coef: 1.4885780486208022},
		}},
	},
}
